#!/bin/sh

if [ "$(basename $0)" = "setenv" ] ; then
  echo "You must source this script, not run it!" 1>&2
  exit 1
fi

if [ -z ${PATH_ORIG} ]; then export PATH_ORIG=${PATH}; fi

export CIRRUS_ARCH=ep9315
export CIRRUS_PLATFORM=ARMV4I
export CIRRUS_KERNEL=linux-2.6

export CIRRUS_BIN=/usr/local/arm/3.4/bin
export CIRRUS_ELF=/usr/local/arm/3.2.1-elf/bin
export PATH=${CIRRUS_BIN}:${CIRRUS_ELF}:/sbin:/usr/sbin:${PATH_ORIG}

echo "CIRRUS_ARCH     : ${CIRRUS_ARCH}"
echo "CIRRUS_PLATFORM : ${CIRRUS_PLATFORM}"
echo "CIRRUS_KERNEL   : ${CIRRUS_KERNEL}"
echo "PATH : ${PATH}"
